import { Article } from '@/types';

// ===== Mock Data for Demo =====
// In production, these come from Cloudflare Worker API

const NOW = new Date().toISOString();

export const MOCK_ARTICLES: Article[] = [
  // TECH
  {
    id: '1',
    title: 'OpenAI 发布 GPT-5：推理能力提升 3 倍，多模态实现质变',
    summary: 'OpenAI 在今天的发布会上展示了 GPT-5 的全新能力。新模型在推理、数学和编程基准测试中提升 3 倍以上，同时多模态理解达到了新的里程碑。AI 专家称这是通用人工智能之路上的重要一步。',
    url: 'https://example.com/gpt5',
    source: '36kr',
    author: '科技观察者',
    publishedAt: new Date(Date.now() - 1800000).toISOString(),
    hotScore: 98,
    category: 'tech',
    tags: ['AI', 'GPT-5', 'OpenAI', '大模型'],
    imageUrl: '/placeholder/tech1.jpg',
    readTime: 5,
  },
  {
    id: '2',
    title: '苹果 Vision Pro 2 曝光：价格降半，重量减 40%',
    summary: '苹果正在开发第二代 Vision Pro，据供应链消息，新设备重量将降低 40%，价格预计降至 $1799。同时，苹果将在 AI 空间计算领域加大投入。',
    url: 'https://example.com/vision-pro-2',
    source: 'weibo',
    author: '数码博主',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    hotScore: 92,
    category: 'tech',
    tags: ['Apple', 'Vision Pro', 'VR', 'AR'],
    readTime: 4,
  },
  {
    id: '3',
    title: '小米汽车 SU7 月销突破 3 万台，超越特斯拉 Model 3',
    summary: '小米汽车公布最新交付数据，SU7 月销量首次突破 3 万台大关，在 20-30 万价位段超越特斯拉 Model 3。雷军在微博表示"接下来要挑战更高目标"。',
    url: 'https://example.com/xiaomi-su7',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 5400000).toISOString(),
    hotScore: 89,
    category: 'tech',
    tags: ['小米', 'SU7', '新能源车', '特斯拉'],
    readTime: 3,
  },
  {
    id: '4',
    title: '字节跳动推出全新视频大模型，对标 Sora',
    summary: '字节跳动发布自研视频生成大模型「即梦AI 2.0」，在视频连贯性、画面质量和生成速度上全面超越现有方案。目前已在抖音内测。',
    url: 'https://example.com/douyin-model',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    hotScore: 85,
    category: 'tech',
    tags: ['字节跳动', '视频AI', 'Sora', '抖音'],
    readTime: 4,
  },
  {
    id: '5',
    title: '国产芯片再突破！华为麒麟 9200 跑分曝光',
    summary: '华为新一代麒麟 9200 芯片安兔兔跑分突破 280 万分，性能接近骁龙 8 Gen 5。预计将在 Mate 80 系列首发搭载。',
    url: 'https://example.com/kirin-9200',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 9000000).toISOString(),
    hotScore: 82,
    category: 'tech',
    tags: ['华为', '麒麟', '芯片', '国产'],
    readTime: 3,
  },
  // FINANCE
  {
    id: '6',
    title: 'A 股突破 4000 点！沪指创年内新高',
    summary: '沪指今日放量突破 4000 点整数关口，成交额突破 1.2 万亿。分析师认为，外资持续流入和政策利好是主要推动力。',
    url: 'https://example.com/a-stock-4000',
    source: 'cls',
    author: '财联社记者',
    publishedAt: new Date(Date.now() - 2400000).toISOString(),
    hotScore: 97,
    category: 'finance',
    tags: ['A股', '沪指', '股市', '投资'],
    readTime: 3,
  },
  {
    id: '7',
    title: '美联储宣布降息 25 个基点，全球股市应声上涨',
    summary: '美联储在今天的议息会议上宣布降息 25 个基点，将联邦基金利率降至 4.25%-4.50% 区间。这是自 2024 年以来的第四次降息。',
    url: 'https://example.com/fed-rate',
    source: 'cls',
    publishedAt: new Date(Date.now() - 4800000).toISOString(),
    hotScore: 90,
    category: 'finance',
    tags: ['美联储', '降息', '利率', '美股'],
    readTime: 4,
  },
  {
    id: '8',
    title: '比特币突破 12 万美元，机构资金加速入场',
    summary: '比特币价格今日突破 12 万美元历史新高，24 小时涨幅超 8%。分析认为美国比特币 ETF 机构资金流入是主要推手。',
    url: 'https://example.com/btc-120k',
    source: '36kr',
    publishedAt: new Date(Date.now() - 6000000).toISOString(),
    hotScore: 88,
    category: 'finance',
    tags: ['比特币', '加密货币', 'ETF', '投资'],
    readTime: 3,
  },
  {
    id: '9',
    title: '央行释放信号：下半年有望再降准降息',
    summary: '央行在季度货币政策报告中释放宽松信号，分析人士预计下半年可能再降准 50 个基点，同时继续引导 LPR 下行。',
    url: 'https://example.com/pboc',
    source: 'cls',
    publishedAt: new Date(Date.now() - 7800000).toISOString(),
    hotScore: 81,
    category: 'finance',
    tags: ['央行', '降息', '货币政策', 'LPR'],
    readTime: 5,
  },
  {
    id: '10',
    title: '美团市值超越京东，成为第三大互联网公司',
    summary: '美团市值在港股交易中首次突破 2000 亿美元，超越京东成为仅次于腾讯和阿里的第三大互联网公司。外卖+到店+即时零售三大引擎持续发力。',
    url: 'https://example.com/meituan',
    source: '36kr',
    publishedAt: new Date(Date.now() - 9600000).toISOString(),
    hotScore: 76,
    category: 'finance',
    tags: ['美团', '京东', '市值', '互联网'],
    readTime: 3,
  },
  // ENTERTAINMENT
  {
    id: '11',
    title: '《流浪地球 3》定档春节，预告片播放量破 2 亿',
    summary: '郭帆导演官宣《流浪地球 3》定档 2027 年春节档，预告片发布 24 小时全网播放量突破 2 亿。网友：终于等到你！',
    url: 'https://example.com/wandering-earth-3',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 1200000).toISOString(),
    hotScore: 95,
    category: 'entertainment',
    tags: ['流浪地球', '电影', '春节档', '郭帆'],
    readTime: 2,
  },
  {
    id: '12',
    title: '周杰伦新专辑《命运》全网首发，3 小时破亿播放',
    summary: '周杰伦第 15 张专辑《命运》正式上线，仅 3 小时全网播放量突破 1 亿。粉丝："我们的青春回来了。"',
    url: 'https://example.com/jay-chou',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 3000000).toISOString(),
    hotScore: 93,
    category: 'entertainment',
    tags: ['周杰伦', '新专辑', '音乐', '华语'],
    readTime: 2,
  },
  {
    id: '13',
    title: '《庆余年 3》开播首日收视率破纪录',
    summary: '《庆余年 3》在腾讯视频开播，首日播放量达到 1.8 亿，创平台剧集开播新纪录。张若昀、李沁等原班人马回归。',
    url: 'https://example.com/joy-of-life-3',
    source: 'tencent',
    publishedAt: new Date(Date.now() - 4200000).toISOString(),
    hotScore: 86,
    category: 'entertainment',
    tags: ['庆余年', '电视剧', '腾讯视频', '张若昀'],
    readTime: 2,
  },
  {
    id: '14',
    title: 'B 站百大 UP 主排名出炉：科技区 UP 主占比创新高',
    summary: 'B 站 2026 年百大 UP 主榜单公布，科技数码类 UP 主占比达到 15%，AI 创作内容首次进入前十。',
    url: 'https://example.com/bilibili-100',
    source: 'bilibili',
    publishedAt: new Date(Date.now() - 5000000).toISOString(),
    hotScore: 79,
    category: 'entertainment',
    tags: ['B站', '百大UP主', '科技', 'AI创作'],
    readTime: 4,
  },
  {
    id: '15',
    title: '国产动画《哪吒 3》定档暑期，导演：这次更震撼',
    summary: '饺子导演在微博官宣《哪吒 3》定档 2027 年暑期档，称"这次的故事和视觉效果都上了一个大台阶"。',
    url: 'https://example.com/nezha-3',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 6600000).toISOString(),
    hotScore: 77,
    category: 'entertainment',
    tags: ['哪吒', '动画', '饺子', '国产'],
    readTime: 2,
  },
  // AI
  {
    id: '16',
    title: 'DeepSeek 发布 V4 开源模型：超越 GPT-5，在数学推理上登顶',
    summary: 'DeepSeek 今日发布开源大模型 V4，在数学推理和代码生成方面全面超越 GPT-5。模型完全开源，可在消费级显卡上运行。',
    url: 'https://example.com/deepseek-v4',
    source: '36kr',
    publishedAt: new Date(Date.now() - 1500000).toISOString(),
    hotScore: 96,
    category: 'ai',
    tags: ['DeepSeek', '开源', '大模型', 'GPT'],
    readTime: 5,
  },
  {
    id: '17',
    title: '马斯克旗下 xAI 融资 100 亿美元，估值达 1500 亿',
    summary: '马斯克的 AI 公司 xAI 完成新一轮 100 亿美元融资，估值达到 1500 亿美元。资金将用于建设更大规模的算力集群。',
    url: 'https://example.com/xai-funding',
    source: '36kr',
    publishedAt: new Date(Date.now() - 4500000).toISOString(),
    hotScore: 83,
    category: 'ai',
    tags: ['xAI', '马斯克', '融资', 'AI'],
    readTime: 3,
  },
  {
    id: '18',
    title: 'AI 生成代码比例达 40%：GitHub Copilot 年化收入破 50 亿',
    summary: 'GitHub CEO 在开发者大会上透露，Copilot 生成的代码占比已达 40%。该产品年化收入突破 50 亿美元，成为微软增长最快的产品。',
    url: 'https://example.com/copilot-revenue',
    source: '36kr',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    hotScore: 80,
    category: 'ai',
    tags: ['GitHub', 'Copilot', 'AI编程', '微软'],
    readTime: 4,
  },
  {
    id: '19',
    title: '教育部：中小学全面开设 AI 基础课程，2027 年秋季起实施',
    summary: '教育部发布通知，要求全国中小学从 2027 年秋季学期起全面开设 AI 基础课程，涵盖 AI 原理、伦理和基础编程。',
    url: 'https://example.com/edu-ai',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 9000000).toISOString(),
    hotScore: 74,
    category: 'ai',
    tags: ['AI教育', '中小学', '教育部', '课程'],
    readTime: 3,
  },
  {
    id: '20',
    title: '百度文心一言 5.0 发布：中文理解力超越 GPT-5',
    summary: '百度发布文心大模型 5.0 版本，中文理解、古文解析和成语使用准确率达 95% 以上。将在百度搜索、小度音箱等产品全面接入。',
    url: 'https://example.com/ernie-5',
    source: 'baidu',
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    hotScore: 73,
    category: 'ai',
    tags: ['百度', '文心一言', '大模型', '中文AI'],
    readTime: 4,
  },
  // SOCIAL / HOT TOPICS
  {
    id: '21',
    title: '上海 2026 世界人工智能大会开幕：全球 200+ 企业参展',
    summary: 'WAIC 2026 在上海世博中心开幕，来自全球 200 多家企业参展。本届主题为「AI 无界·智汇未来」，展览面积 7 万平方米。',
    url: 'https://example.com/waic-2026',
    source: 'sina',
    publishedAt: new Date(Date.now() - 1200000).toISOString(),
    hotScore: 94,
    category: 'social',
    tags: ['WAIC', '上海', 'AI大会', '科技'],
    readTime: 4,
  },
  {
    id: '22',
    title: '多地推进数字人民币试点，线下商户覆盖率达 60%',
    summary: '央行数字货币研究所最新数据显示，数字人民币线下商户覆盖率已达 60%，覆盖餐饮、交通、零售等场景。广州、深圳位列试点城市前列。',
    url: 'https://example.com/dcep',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    hotScore: 84,
    category: 'social',
    tags: ['数字人民币', '央行', '数字货币', '消费'],
    readTime: 3,
  },
  {
    id: '23',
    title: '2026 年高考录取分数线公布：清华北大分数线持平',
    summary: '各省 2026 年高考录取分数线陆续公布，清华、北大在多省录取分数线持平。AI 和新能源相关专业分数线创新高。',
    url: 'https://example.com/gaokao-2026',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 5400000).toISOString(),
    hotScore: 87,
    category: 'social',
    tags: ['高考', '录取分数线', '清华', '北大'],
    readTime: 3,
  },
  {
    id: '24',
    title: '三亚免税店单日销售额创历史新高，暑假游客激增',
    summary: '三亚国际免税城公布数据，7 月 15 日单日销售额突破 8 亿元，创下历史新高。暑假期间日均客流量达 15 万人次。',
    url: 'https://example.com/sanya-duty-free',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    hotScore: 72,
    category: 'social',
    tags: ['三亚', '免税店', '旅游', '消费'],
    readTime: 2,
  },
  // LIFE
  {
    id: '25',
    title: '全国首个「碳中和」社区在上海建成：太阳能供电 + 垃圾全回收',
    summary: '上海浦东新区建成全国首个碳中和社区，社区内所有能源来自太阳能和地热能，垃圾分类回收率达 99%。',
    url: 'https://example.com/carbon-neutral',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 2400000).toISOString(),
    hotScore: 78,
    category: 'life',
    tags: ['碳中和', '上海', '社区', '环保'],
    readTime: 3,
  },
  {
    id: '26',
    title: '「人人都是米其林」：AI 做菜火了，外卖订单反降 30%',
    summary: '多款 AI 烹饪 App 爆红，用户只需拍照食材就能获得详细菜谱。数据显示，安装 AI 做菜 App 的用户外卖频次平均下降 30%。',
    url: 'https://example.com/ai-cooking',
    source: 'weibo',
    publishedAt: new Date(Date.now() - 4800000).toISOString(),
    hotScore: 75,
    category: 'life',
    tags: ['AI', '做饭', '外卖', '生活'],
    readTime: 3,
  },
  {
    id: '27',
    title: '成都大熊猫基地新出生 6 只熊猫宝宝，取名引发全网投票',
    summary: '成都大熊猫繁育研究基地宣布 2026 年上半年新出生 6 只熊猫宝宝，基地发起全网取名投票，24 小时参与量超 500 万。',
    url: 'https://example.com/panda-babies',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 6600000).toISOString(),
    hotScore: 71,
    category: 'life',
    tags: ['大熊猫', '成都', '取名', '可爱'],
    readTime: 2,
  },
  {
    id: '28',
    title: '深圳无人驾驶出租车全面运营，价格比出租车低 40%',
    summary: '深圳全市无人驾驶出租车正式运营，覆盖 80% 市区道路。价格比传统出租车低 40%，首月注册用户突破 200 万。',
    url: 'https://example.com/shenzhen-autonomous',
    source: 'toutiao',
    publishedAt: new Date(Date.now() - 8400000).toISOString(),
    hotScore: 70,
    category: 'life',
    tags: ['无人驾驶', '深圳', '出租车', '自动驾驶'],
    readTime: 3,
  },
];

// Hot topics list (for sidebar)
export const HOT_TOPICS = [
  { id: 'ht1', title: 'GPT-5发布', hotScore: 98, rank: 1 },
  { id: 'ht2', title: 'A股突破4000点', hotScore: 97, rank: 2 },
  { id: 'ht3', title: 'DeepSeek V4开源', hotScore: 96, rank: 3 },
  { id: 'ht4', title: 'WAIC 2026 开幕', hotScore: 94, rank: 4 },
  { id: 'ht5', title: '周杰伦新专辑', hotScore: 93, rank: 5 },
  { id: 'ht6', title: '苹果Vision Pro 2', hotScore: 92, rank: 6 },
  { id: 'ht7', title: '美联储降息', hotScore: 90, rank: 7 },
  { id: 'ht8', title: '小米SU7月销3万', hotScore: 89, rank: 8 },
  { id: 'ht9', title: '比特币12万美元', hotScore: 88, rank: 9 },
  { id: 'ht10', title: '高考分数线公布', hotScore: 87, rank: 10 },
];

// Helper to get articles by category
export function getArticlesByCategory(category: string): Article[] {
  if (category === 'all') return MOCK_ARTICLES;
  return MOCK_ARTICLES.filter(a => a.category === category);
}

// Helper to get article by ID
export function getArticleById(id: string): Article | undefined {
  return MOCK_ARTICLES.find(a => a.id === id);
}

// Helper to get articles by source
export function getArticlesBySource(source: string): Article[] {
  return MOCK_ARTICLES.filter(a => a.source === source);
}